
server:
  port: 8088
spring:
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/angelcuevas/microservices-configs.git
          search-paths: config-data
  application:
    name: config-service